import type { Metadata } from 'next';
import { LegalFooterNav, LegalHeader } from '@/app/terms/page';

export const metadata: Metadata = {
  title: 'Risk Disclosure',
  description: 'Trading risk disclosures for BottomUP users.',
};

const LAST_UPDATED = 'April 25, 2026';

export default function RiskDisclosurePage() {
  return (
    <div className="min-h-screen bg-bg">
      <LegalHeader />
      <main className="mx-auto max-w-3xl px-4 py-12 md:px-8 md:py-16">
        <div className="mono-label">Legal</div>
        <h1 className="mt-2 text-3xl font-extrabold tracking-tight md:text-5xl">
          Risk Disclosure
        </h1>
        <p className="mt-2 text-xs text-fg-dim">Effective: {LAST_UPDATED}</p>

        <div className="mt-8 rounded-2xl border border-rose-400/30 bg-rose-500/[0.06] p-5 text-sm text-rose-200">
          <strong className="block text-rose-300">
            Trading crypto-assets is high-risk. You can lose more than your
            initial deposit. Do not trade with money you cannot afford to
            lose.
          </strong>
        </div>

        <Section id="nature" title="1. Nature of crypto-asset trading">
          <p>
            Crypto-assets are volatile, can be subject to extreme price
            movements within minutes, and are traded on venues that may be
            unregulated, partially regulated, or subject to rules that change
            without notice. Liquidity may dry up, prices may gap, exchanges
            may halt trading, and stablecoins may de-peg.
          </p>
        </Section>

        <Section id="leverage" title="2. Leverage &amp; derivatives">
          <p>
            Perpetual and futures contracts use leverage. Leverage magnifies
            both profits and losses. A small adverse price move can wipe out
            your margin entirely. When used alongside auto-execution, it is
            possible to incur losses faster than you can react.
          </p>
        </Section>

        <Section id="copy" title="3. Copy trading specifics">
          <p>
            Subscribing to a trader, bot, or AI agent means their signals
            will execute in the exchange account you connect. You remain
            fully responsible for the trades executed under your account, even
            though you did not personally initiate them. Creators may
            discontinue a strategy, make mistakes, or experience slippage
            between their signal and your fill. Past performance of any
            creator does not guarantee future performance.
          </p>
          <p>
            Foxy AI can block trades it deems risky, but is not infallible:
            it can fail to block a losing trade, or block a trade that would
            have been profitable. It is an input, not a guarantee.
          </p>
        </Section>

        <Section id="simulated" title="4. Simulated &amp; hypothetical performance">
          <p>
            The &ldquo;$10,000 virtual portfolio&rdquo; feature, leaderboard
            balances, and any other hypothetical performance shown on the
            Service are simulated. They are generated by replaying historical
            trader signals against market prices and do not reflect the
            impact of real-world factors such as slippage, latency, funding
            rates, liquidation cascades, account-level leverage limits,
            exchange outages, or your own psychology. Simulated returns are
            not indicative of returns you would have achieved with real
            capital, and are not indicative of future results.
          </p>
        </Section>

        <Section id="ai" title="5. AI-generated content">
          <p>
            Foxy AI and the Modular Crypto Processors use statistical models
            trained on historical data and public signals. Their outputs can
            contain errors, outdated information, hallucinated facts, or
            biased conclusions. They are not individualized advice and should
            not be the sole basis for any decision involving capital.
          </p>
        </Section>

        <Section id="third-party" title="6. Third-party exchange risk">
          <p>
            BottomUP does not custody your funds. Copy trading is executed
            via your OKX account using credentials you provide. Risks
            associated with OKX — including counterparty default, hacking,
            withdrawal freezes, regulatory actions, or API changes — are
            yours alone. Read OKX&rsquo;s own risk disclosures carefully
            before connecting.
          </p>
        </Section>

        <Section id="tax" title="7. Taxes">
          <p>
            Crypto trading creates taxable events in most jurisdictions.
            BottomUP does not provide tax advice and does not prepare tax
            reports for you. Consult a qualified tax professional.
          </p>
        </Section>

        <Section id="jurisdiction" title="8. Jurisdictional notice">
          <p>
            Copy trading on BottomUP is not currently available to U.S.
            persons. Residents of OFAC-sanctioned countries may not use the
            Service at all. Local laws may prohibit or restrict crypto
            derivatives in your jurisdiction; verify before you trade.
          </p>
        </Section>

        <Section id="ack" title="9. Your acknowledgement">
          <p>
            By using BottomUP you confirm that you have read, understood, and
            accept the risks above; that any trading decisions are yours
            alone; and that BottomUP is not responsible for losses resulting
            from trades executed under your account.
          </p>
        </Section>

        <LegalFooterNav />
      </main>
    </div>
  );
}

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="mt-10">
      <h2 className="text-xl font-bold tracking-tight text-fg md:text-2xl">
        {title}
      </h2>
      <div className="mt-3 space-y-3 text-sm leading-relaxed text-fg-muted [&_strong]:text-fg">
        {children}
      </div>
    </section>
  );
}
